// Mocks generated by Mockito 5.4.6 from annotations
// in nginx_manager_webui/test/providers/backend_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nginx_manager_webui/models/models.dart' as _i2;
import 'package:nginx_manager_webui/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBackendServer_0 extends _i1.SmartFake implements _i2.BackendServer {
  _FakeBackendServer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProxyRule_1 extends _i1.SmartFake implements _i2.ProxyRule {
  _FakeProxyRule_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCertificate_2 extends _i1.SmartFake implements _i2.Certificate {
  _FakeCertificate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthStatus_3 extends _i1.SmartFake implements _i2.HealthStatus {
  _FakeHealthStatus_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAuth() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuth, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadStoredToken() =>
      (super.noSuchMethod(
            Invocation.method(#loadStoredToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.BackendServer>> listBackends({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listBackends, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.BackendServer>>.value(
              <_i2.BackendServer>[],
            ),
          )
          as _i4.Future<List<_i2.BackendServer>>);

  @override
  _i4.Future<_i2.BackendServer> getBackend(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBackend, [id]),
            returnValue: _i4.Future<_i2.BackendServer>.value(
              _FakeBackendServer_0(this, Invocation.method(#getBackend, [id])),
            ),
          )
          as _i4.Future<_i2.BackendServer>);

  @override
  _i4.Future<_i2.BackendServer> createBackend({
    required String? name,
    required String? host,
    required int? port,
    String? protocol = 'http',
    String? description = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBackend, [], {
              #name: name,
              #host: host,
              #port: port,
              #protocol: protocol,
              #description: description,
            }),
            returnValue: _i4.Future<_i2.BackendServer>.value(
              _FakeBackendServer_0(
                this,
                Invocation.method(#createBackend, [], {
                  #name: name,
                  #host: host,
                  #port: port,
                  #protocol: protocol,
                  #description: description,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.BackendServer>);

  @override
  _i4.Future<_i2.BackendServer> updateBackend(
    int? id,
    _i2.BackendServer? backend,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBackend, [id, backend]),
            returnValue: _i4.Future<_i2.BackendServer>.value(
              _FakeBackendServer_0(
                this,
                Invocation.method(#updateBackend, [id, backend]),
              ),
            ),
          )
          as _i4.Future<_i2.BackendServer>);

  @override
  _i4.Future<void> deleteBackend(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBackend, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ProxyRule>> listProxyRules({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listProxyRules, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.ProxyRule>>.value(
              <_i2.ProxyRule>[],
            ),
          )
          as _i4.Future<List<_i2.ProxyRule>>);

  @override
  _i4.Future<_i2.ProxyRule> getProxyRule(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProxyRule, [id]),
            returnValue: _i4.Future<_i2.ProxyRule>.value(
              _FakeProxyRule_1(this, Invocation.method(#getProxyRule, [id])),
            ),
          )
          as _i4.Future<_i2.ProxyRule>);

  @override
  _i4.Future<_i2.ProxyRule> createProxyRule({
    required String? domain,
    required int? backendId,
    String? pathPattern = '/',
    String? ruleType = 'reverse_proxy',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProxyRule, [], {
              #domain: domain,
              #backendId: backendId,
              #pathPattern: pathPattern,
              #ruleType: ruleType,
            }),
            returnValue: _i4.Future<_i2.ProxyRule>.value(
              _FakeProxyRule_1(
                this,
                Invocation.method(#createProxyRule, [], {
                  #domain: domain,
                  #backendId: backendId,
                  #pathPattern: pathPattern,
                  #ruleType: ruleType,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ProxyRule>);

  @override
  _i4.Future<_i2.ProxyRule> updateProxyRule(int? id, _i2.ProxyRule? rule) =>
      (super.noSuchMethod(
            Invocation.method(#updateProxyRule, [id, rule]),
            returnValue: _i4.Future<_i2.ProxyRule>.value(
              _FakeProxyRule_1(
                this,
                Invocation.method(#updateProxyRule, [id, rule]),
              ),
            ),
          )
          as _i4.Future<_i2.ProxyRule>);

  @override
  _i4.Future<void> deleteProxyRule(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProxyRule, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reloadNginx() =>
      (super.noSuchMethod(
            Invocation.method(#reloadNginx, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Certificate>> listCertificates({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listCertificates, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.Certificate>>.value(
              <_i2.Certificate>[],
            ),
          )
          as _i4.Future<List<_i2.Certificate>>);

  @override
  _i4.Future<_i2.Certificate> getCertificate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCertificate, [id]),
            returnValue: _i4.Future<_i2.Certificate>.value(
              _FakeCertificate_2(
                this,
                Invocation.method(#getCertificate, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Certificate>);

  @override
  _i4.Future<void> deleteCertificate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCertificate, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.HealthStatus> getHealth() =>
      (super.noSuchMethod(
            Invocation.method(#getHealth, []),
            returnValue: _i4.Future<_i2.HealthStatus>.value(
              _FakeHealthStatus_3(this, Invocation.method(#getHealth, [])),
            ),
          )
          as _i4.Future<_i2.HealthStatus>);

  @override
  _i4.Future<List<_i2.Metrics>> getMetrics({
    String? metricType = 'requests',
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMetrics, [], {
              #metricType: metricType,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Metrics>>.value(<_i2.Metrics>[]),
          )
          as _i4.Future<List<_i2.Metrics>>);
}
